import { useEffect, useState } from 'react'
import { CheckCircle2, ExternalLink, KeyRound, Save, ShieldCheck } from 'lucide-react'
import { api } from '../api'
import type { AppSettings } from '../types'

export default function SettingsPage() {
  const [settings, setSettings] = useState<AppSettings | null>(null)
  const [secret, setSecret] = useState('')
  const [message, setMessage] = useState('')
  useEffect(() => { void api.settings().then(setSettings) }, [])
  if (!settings) return <div className="page"><p>Ładowanie ustawień...</p></div>
  const research = settings.research
  const setResearch = (patch: Partial<typeof research>) => setSettings({...settings, research: {...research, ...patch}})
  const saveResearch = async () => { await api.saveResearch(settings.research); setMessage('Ustawienia researchu zapisane') }
  const saveAllegro = async () => { const allegro = await api.saveAllegro({...settings.allegro, client_secret: secret || null}); setSettings({...settings, allegro: allegro as AppSettings['allegro']}); setSecret(''); setMessage('Dane Allegro zapisane lokalnie') }
  const test = async () => { try { const result = await api.testAllegro(); setMessage(`OAuth: ${result.oauth}, dostęp listing: ${result.listing_access}`); setSettings(await api.settings()) } catch(e) { setMessage(e instanceof Error ? e.message : 'Test nieudany') } }
  const oauth = async () => { const {url} = await api.oauthUrl(); window.open(url, '_blank', 'noopener,noreferrer') }
  return <div className="page settings-page"><header className="page-header"><div><p className="eyebrow">CONFIGURATION</p><h1>Ustawienia</h1><p>Progi decyzyjne, scheduler i oficjalne połączenie Allegro OAuth.</p></div></header>
    {message && <div className="alert info"><CheckCircle2 size={17}/><span>{message}</span></div>}
    <section className="settings-card"><div className="section-title"><div><h2>Filtry researchu</h2><p>Każdy próg jest stosowany przed nadaniem statusu PASS.</p></div><button className="btn primary" onClick={() => void saveResearch()}><Save size={16}/> Zapisz</button></div>
      <div className="form-grid">
        <NumberField label="Minimalna sprzedaż / popularność" value={research.min_demand} onChange={(v)=>setResearch({min_demand:v})}/><NumberField label="Minimalna liczba sprzedawców" value={research.min_sellers} onChange={(v)=>setResearch({min_sellers:v})}/><NumberField label="Maksymalna konkurencja" value={research.max_competition} onChange={(v)=>setResearch({max_competition:v})}/><NumberField label="Minimalny zysk PLN" value={research.min_profit} onChange={(v)=>setResearch({min_profit:v})}/><NumberField label="Minimalny ROI %" value={research.min_roi ?? 0} onChange={(v)=>setResearch({min_roi:v || null})}/><NumberField label="Prowizja awaryjna %" value={research.commission_rate*100} onChange={(v)=>setResearch({commission_rate:v/100})}/><NumberField label="Pozostałe opłaty PLN" value={research.other_fees} onChange={(v)=>setResearch({other_fees:v})}/><NumberField label="Podatek od ceny %" value={research.tax_rate*100} onChange={(v)=>setResearch({tax_rate:v/100})}/><NumberField label="Cena zakupu min." value={research.purchase_price_min ?? 0} onChange={(v)=>setResearch({purchase_price_min:v || null})}/><NumberField label="Cena zakupu max." value={research.purchase_price_max ?? 0} onChange={(v)=>setResearch({purchase_price_max:v || null})}/><NumberField label="Cena sprzedaży min." value={research.sale_price_min ?? 0} onChange={(v)=>setResearch({sale_price_min:v || null})}/><NumberField label="Cena sprzedaży max." value={research.sale_price_max ?? 0} onChange={(v)=>setResearch({sale_price_max:v || null})}/><NumberField label="Limit wyników" value={research.result_limit} onChange={(v)=>setResearch({result_limit:v})}/><NumberField label="Requesty / sekundę" value={research.requests_per_second} step="0.5" onChange={(v)=>setResearch({requests_per_second:v})}/>
        <label><span>Domyślna fraza</span><input value={research.default_query} onChange={(e)=>setResearch({default_query:e.target.value})}/></label><label><span>Category ID (pojedynczy)</span><input value={research.default_category_id} onChange={(e)=>setResearch({default_category_id:e.target.value})} placeholder="opcjonalnie"/></label><label><span>Kategorie multi-select (ID po przecinku)</span><input value={research.categories.join(', ')} onChange={(e)=>setResearch({categories:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})} placeholder="np. 15998, 15999"/></label>
        <label><span>Automatyczne skany</span><select value={research.scheduler_interval} onChange={(e)=>setResearch({scheduler_interval:e.target.value as typeof research.scheduler_interval})}><option value="manual">Ręcznie</option><option value="hourly">Co godzinę</option><option value="6h">Co 6 godzin</option><option value="12h">Co 12 godzin</option><option value="daily">Codziennie</option></select></label>
      </div>
      <div className="carrier-settings"><span>Akceptowani przewoźnicy</span>{['InPost Paczkomat','InPost Kurier','DPD','DHL','DHL POP'].map((carrier)=><label className="check" key={carrier}><input type="checkbox" checked={research.accepted_carriers.includes(carrier)} onChange={(e)=>setResearch({accepted_carriers:e.target.checked ? [...research.accepted_carriers,carrier] : research.accepted_carriers.filter(x=>x!==carrier)})}/>{carrier}</label>)}<label className="check"><input type="checkbox" checked={research.require_ce_when_applicable} onChange={(e)=>setResearch({require_ce_when_applicable:e.target.checked})}/>Wymagaj CE, jeśli dotyczy</label></div>
    </section>
    <section className="settings-card"><div className="section-title"><div><h2>Allegro API / OAuth</h2><p>Sekret i tokeny trafiają do Menedżera poświadczeń Windows lub szyfrowanego fallbacku.</p></div><span className={`connection ${settings.allegro.connected ? 'ok' : ''}`}><i/>{settings.allegro.connected ? 'Połączono' : 'Niepołączono'}</span></div>
      <div className="api-note"><ShieldCheck size={19}/><div><strong>Ważne ograniczenie danych</strong><p><code>GET /offers/listing</code> wymaga zweryfikowanej aplikacji. Status: <b>{settings.allegro.listing_access}</b>. Bez dostępu live discovery nie udaje wyników — zgłasza ograniczenie.</p></div></div>
      <div className="form-grid"><label><span>Client ID</span><input value={settings.allegro.client_id} onChange={(e)=>setSettings({...settings,allegro:{...settings.allegro,client_id:e.target.value}})}/></label><label><span>Client Secret {settings.allegro.client_secret_configured && '✓ zapisany'}</span><input type="password" value={secret} onChange={(e)=>setSecret(e.target.value)} placeholder={settings.allegro.client_secret_configured ? '•••••••• (bez zmian)' : 'wprowadź sekret'}/></label><label className="wide"><span>Redirect URI</span><input value={settings.allegro.redirect_uri} onChange={(e)=>setSettings({...settings,allegro:{...settings.allegro,redirect_uri:e.target.value}})}/></label><label><span>Środowisko</span><select value={settings.allegro.environment} onChange={(e)=>setSettings({...settings,allegro:{...settings.allegro,environment:e.target.value as 'production'|'sandbox'}})}><option value="production">Production</option><option value="sandbox">Sandbox</option></select></label><label><span>User-Agent</span><input value={settings.allegro.user_agent} onChange={(e)=>setSettings({...settings,allegro:{...settings.allegro,user_agent:e.target.value}})}/></label></div>
      <div className="form-actions"><button className="btn primary" onClick={() => void saveAllegro()}><KeyRound size={16}/> Zapisz dane API</button><button className="btn ghost" onClick={() => void test()}>Test połączenia</button><button className="btn ghost" onClick={() => void oauth()}>Autoryzuj konto <ExternalLink size={14}/></button></div>
    </section>
  </div>
}

function NumberField({label,value,onChange,step='1'}:{label:string;value:number;onChange:(v:number)=>void;step?:string}) { return <label><span>{label}</span><input type="number" step={step} value={value} onChange={(e)=>onChange(Number(e.target.value))}/></label> }
