from __future__ import annotations

from datetime import UTC, datetime

from .domain import CandidateOffer


def demo_candidates() -> list[CandidateOffer]:
    """Deterministic sample-only dataset. Every source is visibly marked DEMO_FIXTURE."""
    now = datetime.now(UTC)
    base = {
        "category_id": "demo-home",
        "category_name": "Dom i Ogród / Organizacja domu",
        "currency": "PLN",
        "active": True,
        "available": 20,
        "source_type": "DEMO_FIXTURE",
        "observed_at": now,
        "generic_evidence": True,
        "ce_evidence": "CE_NOT_REQUIRED",
    }
    return [
        CandidateOffer(
            **base,
            offer_id="demo-pass-source",
            product_id="demo-product-pass",
            ean="5900000000001",
            name="Organizer kuchenny modułowy 6 elementów biały",
            seller_id="demo-seller-source",
            seller_login="demo_source",
            price=43.99,
            delivery_price=8.99,
            carrier="InPost Paczkomat",
            url="https://example.invalid/demo-pass-source",
            image_url=None,
            popularity=8,
            parameters={"Kolor": "biały", "Liczba elementów": "6", "Materiał": "PP"},
        ),
        CandidateOffer(
            **base,
            offer_id="demo-pass-demand-1",
            product_id="demo-product-pass",
            ean="5900000000001",
            name="Organizer kuchenny modułowy 6 elementów biały",
            seller_id="demo-seller-a",
            seller_login="demo_dom_a",
            price=87.90,
            delivery_price=0,
            carrier="DPD",
            url="https://example.invalid/demo-pass-demand-1",
            popularity=125,
            parameters={"Kolor": "biały", "Liczba elementów": "6", "Materiał": "PP"},
        ),
        CandidateOffer(
            **base,
            offer_id="demo-pass-demand-2",
            product_id="demo-product-pass",
            ean="5900000000001",
            name="Organizer kuchenny modułowy 6 elementów biały",
            seller_id="demo-seller-b",
            seller_login="demo_dom_b",
            price=89.99,
            delivery_price=0,
            carrier="DHL POP",
            url="https://example.invalid/demo-pass-demand-2",
            popularity=78,
            parameters={"Kolor": "biały", "Liczba elementów": "6", "Materiał": "PP"},
        ),
        CandidateOffer(
            **base,
            offer_id="demo-fail-source",
            product_id="demo-product-fail",
            ean="5900000000002",
            name="Pojemnik łazienkowy z pokrywą szary 2 l",
            seller_id="demo-seller-c",
            seller_login="demo_lazienka",
            price=42.00,
            delivery_price=10.99,
            carrier="InPost Kurier",
            url="https://example.invalid/demo-fail-source",
            popularity=45,
            parameters={"Kolor": "szary", "Pojemność": "2 l"},
        ),
        CandidateOffer(
            **base,
            offer_id="demo-fail-demand",
            product_id="demo-product-fail",
            ean="5900000000002",
            name="Pojemnik łazienkowy z pokrywą szary 2 l",
            seller_id="demo-seller-d",
            seller_login="demo_lazienka_2",
            price=59.90,
            delivery_price=0,
            carrier="DPD",
            url="https://example.invalid/demo-fail-demand",
            popularity=61,
            parameters={"Kolor": "szary", "Pojemność": "2 l"},
        ),
        CandidateOffer(
            **{**base, "generic_evidence": None, "ce_evidence": None},
            offer_id="demo-verify-1",
            product_id=None,
            ean=None,
            name="Lampka biurkowa dotykowa model L9",
            seller_id="demo-seller-e",
            seller_login="demo_biuro",
            price=29.99,
            delivery_price=None,
            carrier=None,
            url="https://example.invalid/demo-verify-1",
            popularity=None,
            parameters={"Model": "L9", "Kolor": "czarny"},
        ),
    ]
